<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ScrollFix</RootNamespace>
    <AssemblyName>ScrollCapture</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ScrollWaveformControl.cs" Link="ScrollWaveformControl.cs" />
  </ItemGroup>

</Project>
